### ISSUE TITLE
Change event

### ISSUE THREAD

**Issue by sanderus2311** [DavydLiu/DLRadioButton#10]
Hi! Is it possible to change touch action event from UIControlEventTouchDown to UIControlEventTouchUpInside? There is a problem with buttons on scrolling view. When you try to scroll by touching radio button area, event is called but it shouldn't.

**Comment by DavydLiu** [comment]
This is actually a good point, I'll change it and release an update, thanks!

**Comment by DavydLiu** [comment]
Updated to 1.3.3 with change UIControlEventTouchDown to UIControlEventTouchUpInside. Let me know if it works!

**Comment by DavydLiu** [comment]
Closing this issue right now, please feel free to re-open it if the problem still exists.

**Comment by sanderus2311** [comment]
Sorry for long time silence. It works perfect right now : -) Good job.
