### ISSUE TITLE
fails on setOther buttons

### ISSUE THREAD

**Issue by scottf-tvw** [DavydLiu/DLRadioButton#100]
crash with `'-[UIButton setOtherButtons:]: unrecognized selector sent to instance`

buttons in static rows on UITableViewController

```
import UIKit
import DLRadioButton
class VideoSettingsViewController: UITableViewController {

    @IBOutlet weak var videoOrientFollow: DLRadioButton!
    @IBOutlet weak var videoOrientPortrate: DLRadioButton!
    @IBOutlet weak var videoOrientLandscape: DLRadioButton!
    override func viewDidLoad() {
        super.viewDidLoad()
        videoOrientFollow.otherButtons.append(videoOrientPortrate)
        // Do any additional setup after loading the view.
    }
```

same using ref from adding otherButtons outlet collection DLRadioButton's in interface builder

**Comment by DavydLiu** [comment]
Looks like you forgot to set class to `DLRadioButton`.

![set to DLRadioButton](https://github.com/DavydLiu/DLRadioButton/raw/master/Images/change_UIButton_class.png)
