### ISSUE TITLE
Set image size

### ISSUE THREAD

**Issue by Darth-Vladimir** [DavydLiu/DLRadioButton#108]
Not sure if this is something that is just not clear but when I set an image for the selected and unselected state the icon size does not affect the image. I would think by setting the icon size it would change the image view size accordingly. Instead the constraints on the view as a whole affects the icon if an image is set

**Comment by DavydLiu** [comment]
@Darth-Vladimir The icon size doesn't affect image indicator. I'm afraid that you have to adjust the raw image size.
