### ISSUE TITLE
Use of undeclared type 'DLRadioButton'

### ISSUE THREAD

**Issue by andypnz** [DavydLiu/DLRadioButton#110]
Hi. Using Xcode 9, swift. Installed using CocoaPods, using defaults.

Added buttons to storyboard no issue, and I can see them in the simulator.

But when I add 
    @IBOutlet weak var test: DLRadioButton!
    @IBAction func test(_ sender: DLRadioButton) {
}
to my ViewController, I get the error "Use of undeclared type 'DLRadioButton'" for both.....

Any ideas? Thank you.....

**Comment by DavydLiu** [comment]
Did you import `DLRadioButton`?

**Comment by andypnz** [comment]
Actually, no I had not.... 

Adding 'import DLRadioButton' to the ViewController I am using the DLRadioButton's in gave this error: No such module 'DLRadioButton'

But I then added 'import DLRadioButton' to my main ViewController, and all is working....

Thank you! All sorted......
