### ISSUE TITLE
Warnings on Xcode 9, swift 4

### ISSUE THREAD

**Issue by scroll318is** [DavydLiu/DLRadioButton#111]
I'm using the latest version of the library: 1.4.11

I have these warnings:

1. /DLRadioButton.m:71:39: 'userInterfaceLayoutDirectionForSemanticContentAttribute:' is only available on iOS 9.0 or newer

2. 'semanticContentAttribute' is only available on iOS 9.0 or newer in the same place.

Have you fixed these already? When there will be new version with these fixes? Thanks a lot.

**Comment by DavydLiu** [comment]
@scroll318is thx for the report, I updated the example to swift 4 last week didn't get those warnings. Will try it again.

**Comment by ThunderStruct** [comment]
You could wrap it up with an `@available` check to silence the warning.

<img width="713" alt="screen shot 2018-09-24 at 8 38 30 pm" src="https://user-images.githubusercontent.com/18147507/45971652-d4c2b880-c039-11e8-8987-d503f1ed17f5.png">
