### ISSUE TITLE
deselecting all radio buttons...

### ISSUE THREAD

**Issue by andypnz** [DavydLiu/DLRadioButton#112]
Hi. Is there a way to deselect all radio buttons in one go?

Using  'self.button1.isSelected = false' for many buttons is a lot of code :-)

Also, 'self.button1.isSelected = false' only resets (clears) the 'yes' radio button, not the 'no' radio button (they are linked together - one IBAction and IBOutlet)

Thank you!
Andrew

**Comment by DavydLiu** [comment]
Hi @andypnz first of all, `isSelected` is a [getter](https://developer.apple.com/documentation/uikit/uicontrol/1618203-selected) not the setter so setting it will have no effect. Please use `self.button1.selected = false` to deselect it.

For batch deselecting, I guess you can use a for loop, it shouldn't be long.

**Comment by DavydLiu** [comment]
Apparently for Swift 4, `isSelected` is the setter.
