### ISSUE TITLE
Disabled and selected button

### ISSUE THREAD

**Issue by ofer-ebert** [DavydLiu/DLRadioButton#113]
When I change the IsEnabled property of a selected DLRadion button it is grayed out but shows as not selected after enabling the button again it is shown as selected.
I need to see it as disabled and selected how can I do it?

**Comment by DavydLiu** [comment]
For swift, you can use `isEnabled` and `isSelected`.

**Comment by esthrim** [comment]
Same problem with me, isEnabled = false and isSelected = true, but the RadioButton shows as not selected.

**Comment by esthrim** [comment]
@ofer-ebert @DavydLiu 
I've managed to made a workaround for this issue,.
I've created property 
 `@property (nonatomic, getter = isReadOnly) IBInspectable BOOL readOnly`
and then
in the -(void) touchUpInside i added this line 
`if (self.isReadOnly == false) { 
   [self setSelected:YES];
}
`

**Comment by FaridClorida** [comment]
@esthrim How do u manage to set the button as disabled and selected programatically?

**Comment by esthrim** [comment]
@FaridClorida as i have described above,  i added the IsReadonly Property,  so i just set the IsReadOnly to true.
