### ISSUE TITLE
Tableview indexpath problem

### ISSUE THREAD

**Issue by erenozkul** [DavydLiu/DLRadioButton#115]
Hi, i use DLRadioButton in tableview cells. I have 30 cell in table and 4 DLRadioButton each cell. Example if i selected first radio button in first cell,  5., 9., 13., 17., 21., 25. and 29. cell's  first radio button automatically selected.  How i fix this?

**Comment by DavydLiu** [comment]
You need to make sure those cells are not sharing the same radio button. Apparently, you have 4 radio buttons. They are shared by 1-4, 5-8, 9-12, 13-16... Make sure create differently radio buttons for them.

**Comment by erenozkul** [comment]
cells are automatically generated in the custom uitableViewCell class. I'm not sharing the same radio button

**Comment by erenozkul** [comment]
I solved this;
https://stackoverflow.com/a/47429462/5359224
