### ISSUE TITLE
Icon changing once *clicked* is delayed

### ISSUE THREAD

**Issue by nickschafhauser** [DavydLiu/DLRadioButton#119]
Once you click on an icon, it does not change to its "selected" version until you have clicked on something else. It happens in your provided example code as well. I am running Xcode 9.2

**Comment by nickschafhauser** [comment]
![200w_d](https://user-images.githubusercontent.com/27170528/34427737-60fc867e-ec13-11e7-8baf-875ac069901c.gif)

**Comment by nickschafhauser** [comment]
![giphy-downsized-large](https://user-images.githubusercontent.com/27170528/34427746-850f23fa-ec13-11e7-828f-6f59e34e0ee1.gif)

**Comment by DavydLiu** [comment]
@nickschafhauser Thanks for the video, I think the delay comes from the "select animation". So, for the normal radio button (i.e. quality of sleep). There is no delay, right?

**Comment by nickschafhauser** [comment]
@DavydLiu Correct, there is no delay when using normal radio button. It is only when I assign them an icon (like the emojis) that a delay occurs.

**Comment by nickschafhauser** [comment]
@DavydLiu After deploying the app on my physical iphone, there is no delay after selecting a radio button that uses an image. The delay only happens when using the simulator. I will close this issue.
