### ISSUE TITLE
DLRadioButton question

### ISSUE THREAD

**Issue by doubleboss** [DavydLiu/DLRadioButton#12]
I like how the radio buttons in DLRB interact, but I also want a button to deselect if it is selected with a second touch. My intent is for all the buttons to be deselected as when the app first opened. How can DLRadioButton be updated to do this?

Thanks for the help, I am new and learning.

**Comment by DavydLiu** [comment]
Sorry for the delayed response. In the example itself all the buttons are deselected. You shouldn't need to do anything to achieve this.

**Comment by DavydLiu** [comment]
Closing it right now, please feel free to re-open it if the issue persists.
