### ISSUE TITLE
Retain cycle leaks memory

### ISSUE THREAD

**Issue by richardgroves** [DavydLiu/DLRadioButton#125]
After using a set of DLRadioButtons I have a memory leak when the ViewController that was showing them is released. Investigating it is due to the 'otherButtons' array taking a strong reference to each button in it - this setting up a retain cycle meaning the buttons can't dealloc.

I think the 'otherButtons' code needs to be re-written to use an array of weak references to the buttons it holds to allow normal memory releasing to work.

**Comment by DavydLiu** [comment]
@richardgroves Thx for reporting, this should have been fixed in `1.4.12`.
