### ISSUE TITLE
Radio button disappears

### ISSUE THREAD

**Issue by sashberd** [DavydLiu/DLRadioButton#136]
This is the same issue like #94

But in my case when I select custom in button type the button disappears from the XIB at all

![screen shot 2018-05-22 at 17 05 11](https://user-images.githubusercontent.com/11975561/40367526-55963816-5de2-11e8-9f61-01df2768ca05.png)

Just to refresh the problem: When I select the radio button its radio image  disappears and all text is highlighted(like highlighted last button on the print screen)

Here the print screen
![img-0010](https://user-images.githubusercontent.com/11975561/40367851-09095cca-5de3-11e8-9322-5740f6fc0551.PNG)
n from tablet:

**Comment by sashberd** [comment]
@DavydLiu Any help here?
Thanks

**Comment by DavydLiu** [comment]
make sure you button type to `custom`
https://raw.githubusercontent.com/DavydLiu/DLRadioButton/master/Images/change_UIButton_type.png

and don't worry about how it looks like in storyboard if everything is fine when running in the simulator.

**Comment by sashberd** [comment]
@DavydLiu I change the button type to custom and when I run application on my iPad the buttons are not visibled
![img-0013](https://user-images.githubusercontent.com/11975561/40884056-423dc564-6714-11e8-89de-ae0c18af96c4.PNG)

**Comment by sashberd** [comment]
@DavydLiu any suggestions?

**Comment by sashberd** [comment]
**Thanks for your real help!!!**
