### ISSUE TITLE
Set "otherButtons" outlet

### ISSUE THREAD

**Issue by mmrobert** [DavydLiu/DLRadioButton#14]
Hi, good day,

How do I set "otherButtons" outlet? In interface editor or program?

Thanks and have a good one.

Cheng

**Comment by DavydLiu** [comment]
You can do this in either ways.

**Comment by betaSavvy** [comment]
stumble upon this but have no idea how to use it in swift 2 xcode 7.

i tried to do outlet to viewcontroller but has error

**Comment by DavydLiu** [comment]
@betaSavvy Nice, I'm glad it worked for you.
