### ISSUE TITLE
Pre-Select any button Programmatically

### ISSUE THREAD

**Issue by yasirtahir** [DavydLiu/DLRadioButton#15]
Dear,

Thank you for providing very clean code library. 

Well, I am using your code in my SWIFT application. So, I am unable to access the function setSelected(Bool). So, I am looking forward to pre-select any one button from a group of two programmatically. How can I achieve this functionality?

**Comment by DavydLiu** [comment]
In Swift, it should just be boolean `selected`, try to set that to true.

**Comment by DavydLiu** [comment]
e.g. `radioButton.selected = true`

**Comment by yasirtahir** [comment]
Work like a charm. Thank you (Y)
