### ISSUE TITLE
Possible to use as checkbox?

### ISSUE THREAD

**Issue by betaSavvy** [DavydLiu/DLRadioButton#17]
Hi DavydLiu,

Is this possible to be implemented as checkbox button? if so how do we do it in swift as I don't seems to be able to toggle it's state for checked and unchecked display.

**Comment by DavydLiu** [comment]
You can set `isIconSquare` to true if you want to have square button instead of rounded one. However, I don't think it's possible to enable "multiple" selections.

**Comment by betaSavvy** [comment]
yeah i wanted to use it as multiple filter so i needed it to allow multiple selection. Is there any way i can change the state of the button? normally i can do this on the UIButton like myUIButton.selected = !myUIButton.selected but i can't get it to work on DLRadioButton as its always returns selected.

**Comment by DavydLiu** [comment]
Um, currently no, because by definition, radio button shouldn't be able to do multi-selection. Right now, if you set selected to any button within a group of buttons, it will automatically deselect other buttons.

I'm debating whether add an option to enable multiple selection. Since couple of people have opened issue for this.

**Comment by betaSavvy** [comment]
Ok thnx for the answer and would be awesome to have that multiple selection option. At the meantime going to just custom the good old UIButton myself cos the other checkbox frameworks doesn't seems to work well for me.

And thank you for this great piece of work which makes customising so much easier!

**Comment by Remyoman** [comment]
I have a similar issue where I want to use it as a standalone checkbox, but because the class internally always sets itself as selected it's not possible to deselect it.

**Comment by DavydLiu** [comment]
Will add an option to enable multiple selection in this weekend.

**Comment by DavydLiu** [comment]
I added a property `multipleSelectionEnabled` and a method `selectedButtons` in version `1.4.2`, you can enable multiple selection by setting it to `YES`. please let me know if this fixes the issue.

**Comment by betaSavvy** [comment]
awesome! will get back to you after testing it!

**Comment by Remyoman** [comment]
This works for my use case. Thanks for the changes!

**Comment by DavydLiu** [comment]
@Remyoman, great, thx for letting me know. I'll wait for @betaSavvy's feedback to determine whether close the issue.

**Comment by betaSavvy** [comment]
@DavydLiu This works great for my usage too! Really appreciate the time taken to improve on this already great product! 👍👍

**Comment by DavydLiu** [comment]
Thanks for confirming that, I'm glad that it has been helpful. Closing this issue now.

**Comment by ch-muhammad-adil** [comment]
It is not working for my use case. 

Multiple selection attribute should allow only multiple selection but here what is happening if I allow multiple selection than checkbox show up with selection state. At next line if I do 
`isSelected = false` it makes checkbox unselected that is good so far. but than in next line if use `isSelected = true `than it is not selecting checkbox. That is really strange. 

I have 4 checkboxes anyone of them can be selected depending upon server values. 

Let's say 
i do 
```
        checkboxWC.isMultipleSelectionEnabled = true
        checkboxGL.isMultipleSelectionEnabled = true
        checkboxAuto.isMultipleSelectionEnabled = true
        checkboxUmbrella.isMultipleSelectionEnabled = true
```
It make all of them selected by default. 

Than I Have a logic 

           ```
if let wc = request.wc {
                checkboxWC.isSelected = wc.boolValue
            }else {
                checkboxWC.isSelected = false
            }
            if let gl = request.gl {
                checkboxGL.isSelected = gl.boolValue
            }else {
                checkboxGL.isSelected = false
            }
            if let  auto = request.auto {
                checkboxAuto.isSelected = auto.boolValue
            }else {
                checkboxAuto.isSelected = false
            }
            if let umbrella = request.umbrella {
                checkboxUmbrella.isSelected = umbrella.boolValue
            }else {
                checkboxUmbrella.isSelected = false
            }

```

which is pretty simple and straight forward for everyone to understand. But in result i get all of the button in selected state which is set by `isMultipleSelectionEnabled = true`

So I tried this logic as well 

```
        checkboxWC.isMultipleSelectionEnabled = true
        checkboxGL.isMultipleSelectionEnabled = true
        checkboxAuto.isMultipleSelectionEnabled = true
        checkboxUmbrella.isMultipleSelectionEnabled = true
```
Than next 

```
        checkboxWC.isSelected = false
        checkboxGL.isSelected = false
        checkboxAuto.isSelected = false
        checkboxUmbrella.isSelected = false

```

Than my server side values logic 

           ```
if let wc = request.wc {
                checkboxWC.isSelected = wc.boolValue
            }else {
                checkboxWC.isSelected = false
            }
            if let gl = request.gl {
                checkboxGL.isSelected = gl.boolValue
            }else {
                checkboxGL.isSelected = false
            }
            if let  auto = request.auto {
                checkboxAuto.isSelected = auto.boolValue
            }else {
                checkboxAuto.isSelected = false
            }
            if let umbrella = request.umbrella {
                checkboxUmbrella.isSelected = umbrella.boolValue
            }else {
                checkboxUmbrella.isSelected = false
            }

```

Now it display all of the DLRadioButton as **UnSelected** ... :(

**Comment by Axiaomagua** [comment]
i got trouble as this gays  when checkbox isSelected  was init as true ,I cant change the button select status
