### ISSUE TITLE
Release Less Versions

### ISSUE THREAD

**Issue by danielgalasko** [DavydLiu/DLRadioButton#18]
Absolutely love this pod but I find it increasingly frustrating that the version number keeps on incrementing without any good reason

As an example, the latest version `1.4.4` contains just [one commit](https://github.com/DavydLiu/DLRadioButton/commit/b99195dbce7df108dd2cac78475e16d6d3ae50a5) that fixes a bug in the demo project. The demo project should not be impacted by versioning whatsoever.

Please can we take versioning a bit more seriously. Happy to help

**Comment by DavydLiu** [comment]
Very good suggestion, I'll definitely squash some commits before I bump a version number. Sorry for the inconvenience ;)

**Comment by danielgalasko** [comment]
cool bananas!
