### ISSUE TITLE
How to loop through otherButtons for radiobox?

### ISSUE THREAD

**Issue by limeh** [DavydLiu/DLRadioButton#19]
I'm new to swift/ios dev. Came across your library and found it extremely useful. However, I'm wondering if there's a quick way to retrieve the current selection in the group?

For example, i have 4 options A,B,C,D. Can I group them under 'radioGroup1' and just do a radioGroup1.selected or something like that to directly get the value of the selected?

**Comment by DavydLiu** [comment]
Yes, you can set `A.otherButtons = @[B, C, D];`. This will chain all four buttons together. After that, you simply call `selectedButton` on any of these four buttons to retrieve the currently selected one.

**Comment by limeh** [comment]
Hi David,


thanks so much for this. I’m having some problems with ‘otherButtons’. Having assign 11 checkboxes to my primary checkbox (total of 12), the app crashes. I spent some time digging and found that the loop for ‘(void)setOtherButtons’ is really a lot, causing the crash on this line ‘ 
 [radioButton setOtherButtons:[otherButtons copy]];’


Is it meant to be like this? Unfortunately my project requires up to 15 checkboxes so this doesn't work for me ☹












Sent from Windows Mail





From: David Liu
Sent: ‎Friday‎, ‎January‎ ‎8‎, ‎2016 ‎12‎:‎35‎ ‎AM
To: DavydLiu/DLRadioButton
Cc: limeh





Yes, you can set A.otherButtons = @[B, C, D];. This will chain all four buttons together. After that, you simply call selectedButton on any of these four buttons to retrieve the currently selected one.

**Comment by DavydLiu** [comment]
I'll try to chain 15 buttons together later.

**Comment by DavydLiu** [comment]
I was able to reproduce the problem and have fixed it. Will push up the fix tomorrow, stay tuned!

**Comment by limeh** [comment]
Awesome! Thank you so much!


Sent from my Samsung device

-------- Original message --------

**Comment by DavydLiu** [comment]
I've updated it to `1.4.5`, please update to the latest version. Let me know if it fixes the issue!

**Comment by limeh** [comment]
It works like a charm now! Thanks so much. Using 15 with no slow down at all. :)
