### ISSUE TITLE
Failed to render instance of DLRadioButton

### ISSUE THREAD

**Issue by abingeorgev** [DavydLiu/DLRadioButton#21]
I am getting this error everytime I run my project. Using storyboard. Xcode version 7.2.

" Failed to render instance of DLRadioButton: Rendering the view took longer than 200 ms. Your drawing code may suffer from slow performance." And as said, the UI gets stuck for some time.

**Comment by DavydLiu** [comment]
I'm currently using Xcode 7.2 and using storyboard to add `DLRadioButton`, there is no such warnings. However, did you update to `1.4.5`, it fixes performance issues that might cause this warning, if you have a large number of `DLRadioButton`s in your storyboard.

**Comment by abingeorgev** [comment]
Yes am using the latest version.

**Comment by DavydLiu** [comment]
I updated project to `1.4.6`, although never have been able to reproduce the issue you described. Is that possible because you have a huge storyboard which affects rendering of `DLRadioButton`?

**Comment by DavydLiu** [comment]
Closing the issue now, please feel free to re-open it if the issue still exists.
