### ISSUE TITLE
Changing Icon Color

### ISSUE THREAD

**Issue by jrejaud** [DavydLiu/DLRadioButton#25]
Hi David,

Amazing Library thus far.

I have a question regarding tint color and selected icons.

How can I make it so that when a button is selected, it just changes to the image I set in `Icon Selected` without applying a tint color to it or using the tint as part of the transformation?

Thank you,
Jordan

**Comment by DavydLiu** [comment]
Hey Jordan,

Thanks for the pull request. I just merged it, good catch!

I guess the applying of tint color is just default behavior from `UIButton` (`DLRadioButton`'s super class). Can you try to set tint color to clear color?

**Comment by jrejaud** [comment]
I did that, but it changes the color of the image when it isn't selected.

Cheers,
Jordan Rejaud, EIT
M.S. Carnegie Mellon
jordanrejaud.com

**Comment by jrejaud** [comment]
Nvm, I found it.

I needed to set the button style to `Custom` instead of `System`

http://stackoverflow.com/a/27477615/4797412
