### ISSUE TITLE
DLRadioButton with Swift 2

### ISSUE THREAD

**Issue by Hemmingsen** [DavydLiu/DLRadioButton#27]
Can you give an example of how to use checkbox with Swift 2?  I have set up an IBAction outlet and a IBOutlet but there is no intellisense that pops up so I am at a lost where to do from here.  I am a newbie to Swift.  I want to create a checkbox and by default it is not checked.

**Comment by DavydLiu** [comment]
`DLRadioButton` is language agnostics, works fine with both Swift and Objective-C. Not sure what you mean, please be specific about your question.

**Comment by DavydLiu** [comment]
Will add an example for swift this weekend.

**Comment by andreichirkunovgoon** [comment]
Great! Thank you! Looking forward to it as well.

**Comment by andreichirkunovgoon** [comment]
Especially if you could quickly show how to do it programmatically in swift

**Comment by DavydLiu** [comment]
I've added an example for how to use `DLRadioButton` with swift, please pull the latest demo project and let me know if you have any questions. Thx!

**Comment by Hemmingsen** [comment]
I have tried to build the project with xcode 7.2 but I get three error messages:

- Expected expression in list of expressions
- Expected ´,´separator
- Missing argument for parameter "action" in call

` radioButton.addTarget(self, action: #selector(DemoViewController.logSelectedButton), forControlEvents: UIControlEvents.TouchUpInside);`

Have you seen these error messages before when building the project?
