### ISSUE TITLE
RTL languages autolayout not working fine

### ISSUE THREAD

**Issue by RajChanchal** [DavydLiu/DLRadioButton#28]
In Arabic Language (A RTL language), the alignment is not fine. See Screenshot 
<img width="385" alt="screen shot 2016-04-01 at 4 18 32 pm" src="https://cloud.githubusercontent.com/assets/7058465/14205564/8b700dba-f825-11e5-9120-0f3f80ad4d2f.png">

**Comment by DavydLiu** [comment]
Hi Raj,

Thanks for submitting it, will take a look later today.

**Comment by DavydLiu** [comment]
Hi Raj,

I updated `DLRadioButton` to `1.4.7` and fixed this issue. Please update to this version, and let me know if it works.

**Comment by RajChanchal** [comment]
thanks DavydLiu for the new version. I tried this, it has become better than before. But it has still the problem of alignment. Let me show you how. Storyboard constraints (I am supporting two languages: English and Arabic)
<img width="575" alt="screen shot 2016-04-03 at 6 38 45 pm" src="https://cloud.githubusercontent.com/assets/7058465/14232688/b50c530c-f9cb-11e5-97b8-09e352b18ddd.png">

This is how it appears in Arabic:
<img width="312" alt="screen shot 2016-04-03 at 6 43 25 pm" src="https://cloud.githubusercontent.com/assets/7058465/14232699/05f3554a-f9cc-11e5-81e6-ea98569e067a.png">

This is how it appears in English: 
<img width="322" alt="screen shot 2016-04-03 at 6 46 05 pm" src="https://cloud.githubusercontent.com/assets/7058465/14232709/65a05254-f9cc-11e5-9e47-04f76078f210.png">

It doesn't seem to mirror in Arabic, a RTL language.

**Comment by DavydLiu** [comment]
I don't think it is related to `DLRadioButton`, since it doesn't add any auto layout constrains programmatically. It looks like me there are contradictory constrains here (trailing space to super view: 20 and leading spacing to super view: 20). You should only specify leading space in this case (i.e. don't add constrains specific for RTL languages).

**Comment by DavydLiu** [comment]
Also, making sure that you set the content alignment to the correct way.

**Comment by DavydLiu** [comment]
Close it for now, feel free to re-opne it still has issue.

**Comment by oduysmara** [comment]
i have the same problem.
Kindly  solve this problem
