### ISSUE TITLE
How to select a button programmatically? 

### ISSUE THREAD

**Issue by smidaharoun** [DavydLiu/DLRadioButton#29]
How to set a radio button selected by default programmatically?

**Comment by DavydLiu** [comment]
`DLRadioButton` is a subclass of `UIControl`. You can simply set `selected` property to `YES`.

**Comment by smidaharoun** [comment]
and how to select '`otherButtons`' ?

**Comment by DavydLiu** [comment]
Same, you get one of the `otherButtons` and set its `selected` to `YES`.

**Comment by abdymm** [comment]
@DavydLiu what doyou mean selected to YES ? in programmatically?
