### ISSUE TITLE
Not working inside a UIScrollView

### ISSUE THREAD

**Issue by guidev** [DavydLiu/DLRadioButton#30]
Hello,
The button does not work if added to a UIScrollView, do you have any idea why?

**Comment by DavydLiu** [comment]
I know there are other developers use it in UIScrollView and it works well. Can you provide an example?

**Comment by guidev** [comment]
never mind, my fault. I don't know how but it was outside of the scrollview content (still visible though)

**Comment by guidev** [comment]
I have another question...

I need only one button, but once I tap on it, it stays selected, even if I tap on it again. 
Is this the intended behavior?

**Comment by DavydLiu** [comment]
Yes, this is intended behavior for all radio buttons. You can only deselect by selecting other buttons. However, if you do want to toggle button's selection state by tapping. You can do this programmatically (basically, check if button is selected when received touch event, if selected set `selected` to `NO` and vise versa. e.g. `radioButton.selected = !radioButton.selected`).
