### ISSUE TITLE
Radio icon only appear after selecting particular button

### ISSUE THREAD

**Issue by manan280194** [DavydLiu/DLRadioButton#31]
First of all thank you for creating DLRadioButton. The issue I want to discuss is as below.

I have added two radio buttons. Buttons are added using interface builder. 

When the view loads up the round  icon on the left of the button does not show.
But when I select the button round icon shows for that button and same for other button.

Once they are appeared both works fine.

I don't understand what is the problem. Help me here.
Thanks.

**Comment by DavydLiu** [comment]
Did you change the UIButtons' type to "custom"?

**Comment by manan280194** [comment]
Yes. But its not working

**Comment by DavydLiu** [comment]
That sounds weird. Is there any chance that you can attach the project so that I can take a look at it?

**Comment by DavydLiu** [comment]
Closing for now, please feel free to reopen it.

**Comment by manan280194** [comment]
Thanks for your response. I have finally found the problem (Not in class but in implementation) and solved it in my way. I have explained here about how I was using it in my project and solution of my own.

The `UIView` contains a `UISwitch` which is initially OFF. There is another view containing two DLRadioButtons. 

**Implementation:**
When the switch is OFF, the view should not display and when switch is ON, the view appears.

For that I have used height constraint for the view that appear/disappear according to the state of the switch.

In the `viewDidLoad` method one method is called which manages the height constraint of the view. So when the view loads up view disappear. And when I switch ON the view appear but the icon on left side of the radio button does not appear.

**Solution**
I set the `UISwitch` initially ON and call the method to handle the view in `viewDidAppear`. Which will make the view disappear. 

So when I switch ON while running, the radio buttons works perfectly.

I still don't know the exact problem. But it seems that the buttons needs to be loaded when the view appears.

I have written my whole scenario thinking it might help you to solve the problem (If there is any). 

Thanks again. Have a great day.

**Comment by DavydLiu** [comment]
The icon will only display if `drawRect` is invoked. Is there any particular reason that you hide the view by setting the height constraint? Why not use `hidden` property instead?

Also, try call `setNeedsDisplay` on `DLRadiobutton` when you change the height constrain of its super view.

**Comment by manan280194** [comment]
The reason for using height constraint is that the super view of `DLRadioButton` is inside of  `UIScrollView` and it occupies the space of the view if I use `hidden` property.

I also tries `setNeedsDisplay` on `DLRadioButton` in `viewDidAppear` when the height is changed. I  used outlet connection of the main radio button but the `drawRect` does not get called.
