### ISSUE TITLE
How to change a selected radio's color

### ISSUE THREAD

**Issue by voquanghoa** [DavydLiu/DLRadioButton#32]
Hello,

I'm using this library in my project (Swift) and I don't know how to change to color of a selected radio in runtime.

This is before 
<img width="23" alt="screen shot 2016-04-22 at 4 30 27 pm" src="https://cloud.githubusercontent.com/assets/10450325/14737690/95ae1ba4-08a7-11e6-8007-8f4f44ae9537.png">
After
<img width="24" alt="screen shot 2016-04-22 at 4 30 39 pm" src="https://cloud.githubusercontent.com/assets/10450325/14737696/9c4837ec-08a7-11e6-8dd5-5923ba4d9429.png">

You can see color of the third radio button (selected) does not change. 

This is how I tried to change the color.
```swift
func setButtonColor(button: UIButton, color: UIColor){
        button.setTitleColor(color, forState: UIControlState.Disabled)
        button.setTitleColor(color, forState: UIControlState.Normal)
        button.setTitleColor(color, forState: UIControlState.Highlighted)
        button.setTitleColor(color, forState: UIControlState.Selected)
        button.setTitleColor(color, forState: UIControlState.Reserved)
        button.setTitleColor(color, forState: UIControlState.Focused)
        button.setTitleColor(color, forState: UIControlState.Application)
 }
```
Please help me solve this problem.
Thank you.

**Comment by DavydLiu** [comment]
You can simply use 

```
button.iconColor = /* the color you want */
button.indicatorColor = /* the color you want */
```

But, it's a bit strange that setting title color didn't work. Because title color is the default color.

**Comment by voquanghoa** [comment]
Thanks for your response. It's work!
