### ISSUE TITLE
How Do I Show a radio button selected by default?

### ISSUE THREAD

**Issue by irshadq24** [DavydLiu/DLRadioButton#34]
Thank for the great work..! I was just concern about how do I show a radio button selected by default because all the buttons are deselected by default and the user may or may not be clicking on the radio button because I cannot force them to do so . Thats why I just want that any of the radio group button should be shown as selected by default. Is there any way to do this??

Thanks

**Comment by DavydLiu** [comment]
I think you can simply set `selected` to `YES`.

**Comment by irshadq24** [comment]
Hello DavydLiu,
Actually the thing is I already tried from the storyboard in attribute inspector, I set the State Config to Selected but nothing happened thats why I didn't even tried to do programmatically (my bad) and asked you guys about it thanks a lot for helping me out here between very good work nicely implemented thanks for this library.

Regards

**Comment by DavydLiu** [comment]
Just tried select it in attribute inspector, it works.

**Comment by abs1010** [comment]
Changing in the attribute inspector did't work for me, so I adde it programatically as follows:
In the ViewDidLoad method
self.yourRadioButton.isSelected = true
