### ISSUE TITLE
Getting value from database, how do I show selected DLRadioButton?

### ISSUE THREAD

**Issue by Steve423** [DavydLiu/DLRadioButton#35]
Example, I have 3 radio buttons, ( Goat tag with 1, Horse tag with 2, Cow tag with 3). User selected Horse , which saves "2" in the database. User goes back to edit record, how can I show "Horse" was selected?

Thanks.

**Comment by DavydLiu** [comment]
Not sure I get the question. You want to show Horse was selected before? I think you need to store this information (which button user selected before) in you controller and set the corresponded button's `selected` to `YES`. Hope this helps.

**Comment by Steve423** [comment]
Example, yesterday user selected "Horse" and "2" was saved in database. Today user will edit record by reading in "2" from database.
How do I store that info( the "2") in my controller and set button "selected" to "YES"  so that the screen today will show "Horse" selected , just like "Horse" was selected on yesterday's screen?

**Comment by DavydLiu** [comment]
This shouldn't be the responsibility of UIControl. However, you can use `NSUserDefault` to store any persistent value. Please refer to [this doc](https://developer.apple.com/library/mac/documentation/Cocoa/Reference/Foundation/Classes/NSUserDefaults_Class/index.html) for more information.

**Comment by Steve423** [comment]
As a newbie, I have already spent several hours on this . A code snippet  would be GREAT!

**Comment by Steve423** [comment]
Here is what worked for me- so **far.- I hope this helps someone else**
On RadioButton, I select '"Reference outlet" and I had
@property (weak, nonatomic) IBOutlet UIButton *horsepr;

In *.m code, in viewDidLoad, I call routine which has 
  ...
  switch (mychosen){
     case 2:{
            UIButton *buttonhorse = self.horsepr;
            [ buttonhorse setSelected:YES];
      }  break;
      default:.....
