### ISSUE TITLE
DLRadioButton problem

### ISSUE THREAD

**Issue by PiotrStepien** [DavydLiu/DLRadioButton#36]
Hi!

I installed DLRadioButton using cocoapods and when I try to add button to my storyboard and set the class to DLRadiobutton I receive an information about 3 issues. Screenshot bellow:
<img width="252" alt="zrzut ekranu 2016-06-02 o 19 12 34" src="https://cloud.githubusercontent.com/assets/16884253/15753940/202aa608-28f6-11e6-8682-5478122a9783.png">

How can I solve this problem and use your framework?

**Comment by DavydLiu** [comment]
Can you double check that you've added DLRadioButton in "Link Binary With Libraries" of Build Phrases for your target?

**Comment by PiotrStepien** [comment]
it looks like that 
<img width="870" alt="zrzut ekranu 2016-06-02 o 19 20 33" src="https://cloud.githubusercontent.com/assets/16884253/15754161/207debbe-28f7-11e6-868f-52f67f0c6f5a.png">

**Comment by DavydLiu** [comment]
Can you click on "+" and select DLRadioButton from the list?

**Comment by PiotrStepien** [comment]
the problem is -> there is no DLRadioButton
<img width="404" alt="zrzut ekranu 2016-06-02 o 19 23 39" src="https://cloud.githubusercontent.com/assets/16884253/15754245/9684a5b4-28f7-11e6-8b1c-816fdafe2fba.png">

my pod file looks like that:

# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'radioButton' do

pod 'DLRadioButton', '~> 1.4'

end

**Comment by DavydLiu** [comment]
libDLRadioButton.a is what you're looking for.

**Comment by PiotrStepien** [comment]
it still doesne't work. I have a problem with build the project.

<img width="1425" alt="zrzut ekranu 2016-06-02 o 19 28 04" src="https://cloud.githubusercontent.com/assets/16884253/15754384/3c56420e-28f8-11e6-95e3-5bf58b4afc86.png">

link binary looks like that:
<img width="735" alt="zrzut ekranu 2016-06-02 o 19 29 20" src="https://cloud.githubusercontent.com/assets/16884253/15754410/56cfc18c-28f8-11e6-970f-e129e14e9783.png">

**Comment by DavydLiu** [comment]
Have you tried clean build by pressing cmd + option + shift + k and build again?

**Comment by PiotrStepien** [comment]
yeap, and nothing:( my code as attachment if you would like to see how it's look like:)
[radioButton.zip](https://github.com/DavydLiu/DLRadioButton/files/296172/radioButton.zip)

**Comment by PiotrStepien** [comment]
if you will be have a time, can you look at my project and check what do I make wrong with this framework please?

**Comment by PiotrStepien** [comment]
I solved this problem. In pod file I had to use this line of code:

      use_frameworks!

    pod 'DLRadioButton', '~> 1.4'

    end
