### ISSUE TITLE
rendering took too long?

### ISSUE THREAD

**Issue by tahoecoop** [DavydLiu/DLRadioButton#37]
Hello, first of all thanks for the great code! In my storyboard, I get the error `error: IB Designables: Failed to render instance of DLRadioButton: Rendering the view took longer than 200 ms. Your drawing code may suffer from slow performance.` The app runs but the red error is always there. Is anything affecting performance, and any way to get rid of this error? Thanks again!

**Comment by DavydLiu** [comment]
Thx for reporting, will take a look in this weekend.

**Comment by dwjdwj1216** [comment]
I met this problem too. The interesting thing is that I do noting and it gone. If you find the problem, please tell me too. Thanks for you work.

**Comment by DavydLiu** [comment]
I had this issue intermittently a while ago, it seems to resolve itself after building the project. I couldn't reproduce it on my Mac. Can anyone of you consistently reproduce it?

**Comment by tahoecoop** [comment]
The problem went away for now, definitely seems to come and go. Well, I'll post if any more info on my end, but looks ok for now. Thanks again!!
