### ISSUE TITLE
radio buttons don't select properly

### ISSUE THREAD

**Issue by kevinossia** [DavydLiu/DLRadioButton#38]
When I tap a radio button, it highlights the text next to it in a rectangle, rather than filling in the circle with the indicator.

**Comment by DavydLiu** [comment]
Please make sure `indicatorColor` is set.

**Comment by kevinossia** [comment]
I set indicatorColor to dark text color, and it still gives the same result.

**Comment by DavydLiu** [comment]
You might have set the `iconSelected`, if so the icon will not be drawn. You can validate by setting a breakpoint in `DLRadioButton.m` line 77 to see if it hits it.

**Comment by kevinossia** [comment]
The breakpoint showed that selected was false. Every time I hit resume, selected gets switched between true and false. In the interface builder, iconSelected wasn't set to anything.

**Comment by kevinossia** [comment]
The button type wasn't set to custom...fixed.
