### ISSUE TITLE
RadioButton showing only after selection

### ISSUE THREAD

**Issue by faileon** [DavydLiu/DLRadioButton#39]
Hi, I have a small problem with your library. The radio button only appear after I select it for some reason.
As shown on screenshot below:

Any idea what is going on? Thanks :)

**Comment by DavydLiu** [comment]
Sorry for the laaate response. Are you still having this issue? From the code, I didn't notice any issue except for setting `contentHorizontalAlignment`.

**Comment by faileon** [comment]
I did not figure out the problem so I implemented my own radio buttons. Thanks for the reply tho :)

**Comment by DavydLiu** [comment]
Welcome, closing it for now.
