### ISSUE TITLE
setVisibility option

### ISSUE THREAD

**Issue by igalfsg** [DavydLiu/DLRadioButton#43]
Hi, First of all thanks for your great work. Do this buttons have a setVisibility option or something like that? because when I use .hidden I can hide the button but when I set it equal to false the button doesn't appear again.

Thanks

**Comment by DavydLiu** [comment]
`DLRadioButton` does not have a `visibility` property. It's a subclass of `UIButton`, hence use `hidden` to control its visibility. Please remember that once a UIView is hidden or alpha is set to 0, it no longer receives touch event.

**Comment by igalfsg** [comment]
hi thanks for your quick reply, have you had problems using the hidden function? because it disapears wether I put equal true or false and I cant get them to show again

**Comment by DavydLiu** [comment]
No, I didn't have this problem. It should work exactly as a regular `UIView` in terms of hide and show.

**Comment by igalfsg** [comment]
I am sorry I just realize that I dragged the show button to both functions so it was hiding it because it was calling that function to. thanks for your help and once again great work

**Comment by DavydLiu** [comment]
You're most welcome, please spread the word if like `DLRadioButton`, closing this issue for now.
