### ISSUE TITLE
Connecting DLRadioButton to Swift

### ISSUE THREAD

**Issue by jbelr** [DavydLiu/DLRadioButton#46]
I went through the procedure to establish a Podfile containing DLRadioButton. I follow what you are saying about putting a button on my storyboard and changing it to a custom one of DLRadioButton. But it doesn't seem to be able to find the DLRadioButton as an object. Somehow I'm not putting DLRadioButton into the Podfile in such a manner that Swift is able to locate it or am not inserting a proper syntax in my storyboard file to refer to it. My Podfile contains:

# Uncomment this line to define a global platform for your project

platform :ios, '9.0'

target 'ageCalculator' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ageCalculator

    pod 'DLRadioButton', '~> 1.4'

end

Might you have any idea of where I went astray? Any help would be greatly appreciated.

Thanks...

John

**Comment by jbelr** [comment]
I uncommented the line shown above but when I go to the Custom Class drop down DLRadioButton is not shown.

**Comment by DavydLiu** [comment]
Sorry for the late reply, by uncommenting `use_frameworks!`. It should work with `Swift`.
