### ISSUE TITLE
set mutiple to yes there was an exception

### ISSUE THREAD

**Issue by jessefang** [DavydLiu/DLRadioButton#47]
when i set the mutiple to yes ,there was came out a exception :-[UIImage selectedButtons]: unrecognized selector sent to instance 0x7fd3aca57050,but when set the mutiple to no ,it's worked fine

**Comment by DavydLiu** [comment]
It sounds like you are asking an UIImage for selectedButtons. Did you happen to send this message to the icon image instead of radio button itself?
