### ISSUE TITLE
Use As Toggle

### ISSUE THREAD

**Issue by justinackermann** [DavydLiu/DLRadioButton#48]
Hi,

Love this! However I cannot figure out how to use the checkbox as a toggle? For instance just have one checkbox and have it selectable and unselectable. Maybe I am just overlooking something simple!

Thanks!

**Comment by DavydLiu** [comment]
Thanks! Try to set `multipleSelectionEnabled` to `YES`.

**Comment by justinackermann** [comment]
Should have read closed issue first. My bad! Thanks for help with something already answered though and not yelling at me for being dumb! haha
