### ISSUE TITLE
Redraw button on color changes

### ISSUE THREAD

**Issue by Remyoman** [DavydLiu/DLRadioButton#5]
I am using this control in a way where the selected and not selected states have different colors besides the inner circle being drawn.
If you change the icon or indicator color the buttons aren't redrawn using the new colors.

It would be nice to see the addition to be able to set a color for the selected state.
Another way would be to force a redraw if the colors of the control have changed.

The workaround I found was to set the icon or iconselected to nil and calling setNeedsDisplay to force a redraw for the newly assigned color. Which seems to me as a bit hacky.

**Comment by DavydLiu** [comment]
Great suggestion! I'd be tentative to add an new API for selected color. But I'll add force redraw if any color or size changed.

**Comment by Remyoman** [comment]
@DavydLiu That sounds reasonable, thanks for the quick response!

**Comment by DavydLiu** [comment]
Updated to 1.3.2, I figured out the most elegant solution would be using UIButton's title color for selected color.

Basically, you only need to set a different title color for the Radio button. That's it. Let me know if this works.

**Comment by Remyoman** [comment]
Works great, this was exactly what I wanted it to behave. Thanks again for the quick update!

**Comment by philipborbon** [comment]
Is there any way to change **iconColor** and **indicatorColor** after the button is drawn regardless if it's selected or not?
