### ISSUE TITLE
Problem creating widget

### ISSUE THREAD

**Issue by itraxAdmin** [DavydLiu/DLRadioButton#50]
Hi, I'm using Xcode 7.3. I just added the DLRadioButton.m and DLRadioButton.h on my project as said on option 1 of the installation guide.
I was able to assign the class DLRadioButton to a button and compile the application. However when I import DLRadioButton on my swift code in order to create a widget I got an error saying that the DLRadioButton module does not exists. 
My code was written in swift.

What can I do?

Thanks

**Comment by itraxAdmin** [comment]
I'd try to install using the option 3 of installation guide. The Cartfile method and now the DLRadioButton module can be used in my swing code. However when I try to compile I get this error message.

dyld: Library not loaded: @rpath/DLRadioButton.framework/DLRadioButton
  Referenced from: /Users/Flavio/Library/Developer/CoreSimulator/Devices/7E111F56-A3AF-4254-A61C-7C8026CE0D56/data/Containers/Bundle/Application/B464AFDF-DF4F-4338-80E5-B4E6C789C368/VanCool.app/VanCool
  Reason: image not found

What can I do?

Thanks.
Flavio

**Comment by DavydLiu** [comment]
If you are using `Swift`, try add `use_frameworks!` in your pod file. Let me know if it works, for more information about that, please visit: https://blog.cocoapods.org/CocoaPods-0.36/
