### ISSUE TITLE
Suggested improvement

### ISSUE THREAD

**Issue by mheins57** [DavydLiu/DLRadioButton#51]
Thanks for your nice DLRadioButton package.  I made one improvement to a copy of your software which I'll suggest in case you want to add it.  Basically I took out the otherButtons array and replaced them with a single mutable set shared among all buttons in a group, added a new -groupWithButton: method, and changed a few places internally to use the set rather than the arrays.  If you want the change, let me know and I'll be glad to provide it.  Thanks.

**Comment by DavydLiu** [comment]
Hi mheins57,

I think it's a great idea to use `set` instead of `array` for the buttons. Also `groupWithButton:` is a more intuitive way for grouping buttons. However, these would introduce breaking changes. Thanks for the suggestion!
