### ISSUE TITLE
radio button

### ISSUE THREAD

**Issue by jihadkahil** [DavydLiu/DLRadioButton#52]
how can i choose only one radio button and unselect other using swift

**Comment by DavydLiu** [comment]
You can simply set `selected` to `true` for that button if you're using swift.

**Comment by jihadkahil** [comment]
Thank you fro your support

**Comment by jihadkahil** [comment]
https://docs.google.com/forms/d/1GKTv271bKITc49A-BOq6nT55vHInzb8fu45ahkbSOrs/edit
