### ISSUE TITLE
How to set the options in interface builder

### ISSUE THREAD

**Issue by CyberMew** [DavydLiu/DLRadioButton#53]
I am unable to find this section: https://github.com/DavydLiu/DLRadioButton/raw/master/Images/design_DLRadioButton.png

I'm on Xcode 7.3.1

**Comment by SamDecrock** [comment]
This only happens after you put "DLRadioButton" as the class name of the UIButton

**Comment by DavydLiu** [comment]
@SamDecrock 👍, thanks!
