### ISSUE TITLE
Radio button inside cell selects button in other cells

### ISSUE THREAD

**Issue by ajoshdee** [DavydLiu/DLRadioButton#56]
Hi, i'm trying to put my radio button inside a prototype cell, my problem is that when i pressed a radio button for example in cell 1, the radio button in cell 9 also gets selected. how do i solve this issue?

**Comment by DavydLiu** [comment]
As long as each radio button in the cell is a **separate instance**. The problem should be resolved.

**Comment by ajoshdee** [comment]
how do you make it into a separate instance? I'm creating a set of radio buttons inside a prototype cell. So those buttons will be dequeued and used again. I think that is what's happening.

**Comment by DavydLiu** [comment]
One option is having an array of sets of radio buttons. You can fetch corresponded set of buttons by using cell index.
