### ISSUE TITLE
Only one Button in TableviewCell

### ISSUE THREAD

**Issue by saipavanparanam** [DavydLiu/DLRadioButton#59]
I have only one button in tableviewcell, now how i can use your radio button, when i click on the button it gets selected and stays that way. It doesn't get deselected. Also button in all rows can be selected. What I want is whenever i click on another button I want to deselect any selected button in other row

**Comment by DavydLiu** [comment]
Sounds like to me that you don't have separate instance of radio buttons in each cell. The button in all the cells is actually the same radio button instance. That's why they get selected simultaneously.

Please create individual radio button for each cell, and group them together by setting the `otherButtons`.

**Comment by ikyh** [comment]
@DavydLiu How can we create separate instances for every cell?. What if the cells are dynamic.? I have the same issue. I am rendering numberOfRows dynamically, according to array count in JSON. I have only one radio button in a cell. If I select another button, the previously selected button should get deselected. Please help. What can be done?

**Comment by saipavanparanam** [comment]
@ikyh hi Ipek, what you can do is declare an int variable globally and gives its value as -1 .
In the did select row method, assign the indexparth.row value to the variable . and reload table data
In didDeselect row method assign -1 again to the variable. and reload table data
now in cellforRow method, write a method so that  the radio button whose indexPath.row is equal to the declared variable get selected, and others dont get selected. 
Intitally there is no row selected, hence no buuton is selected. when you select one row, then variable value is assigned and button gets selected.

**Comment by saadHassine** [comment]
I would like to know if anyone had an issue of putting a Radio Button inside dynamic tableView cells because every radioButton I have comports on his own
