### ISSUE TITLE
Icon Squre not working iOS 10

### ISSUE THREAD

**Issue by zanesc** [DavydLiu/DLRadioButton#63]
I haven't tried on any other iOS so i can only speak for iOS 10. The Icon Square option in Interface Builder (assuming this is supposed to keep the check box squared) does not work. My icon remains stretched no matter what i set this option to.

**Comment by DavydLiu** [comment]
Did you try it in simulator? Sometimes interface builder can be funky.

**Comment by DavydLiu** [comment]
Tested on iOS 10, works as expected.
