### ISSUE TITLE
Icon not visibile in Interface Builder

### ISSUE THREAD

**Issue by zanesc** [DavydLiu/DLRadioButton#64]
Again, I have only tried this on iOS 10 so I can not speak for other iOS/Xcode builds. The icon does not appear on interface builder. Also the text starts off as white colour so it is not visible either until you change the text colour. Should default to black in my opinion. When you build the app however, it works.

**Comment by DavydLiu** [comment]
The default color shouldn't be white though. I've seen icon didn't rendered in Interface Builder, not sure why.
