### ISSUE TITLE
layout problem

### ISSUE THREAD

**Issue by captain-black** [DavydLiu/DLRadioButton#65]
![image](https://cloud.githubusercontent.com/assets/1026515/19835187/8bfae3be-9eb9-11e6-8b21-8c40213d1151.png)
after I set icon and iconSelected, the titleLabel's layout not well

**Comment by DavydLiu** [comment]
Increase width of the icons should fix the issue. Or try to update the constrains.

**Comment by chanonly123** [comment]
Any auto width possibility?

**Comment by DavydLiu** [comment]
@chanonly123 can you elaborate what do you mean by auto with? thx

**Comment by chanonly123** [comment]
I mean automatic sizing of button to fit its contents.

**Comment by DavydLiu** [comment]
try to call `sizeToFit` on it?
