### ISSUE TITLE
How do I redraw radio button with fill custom color in disable mode?

### ISSUE THREAD

**Issue by furueili** [DavydLiu/DLRadioButton#7]
as title, please give me some help just  like below image thx

![img_7437](https://cloud.githubusercontent.com/assets/1407724/8974028/83b232b2-369f-11e5-8105-6f4f1fbff1de.JPG)

**Comment by DavydLiu** [comment]
If you only want set title text color for disabled state. You can use `setTitleColor:forState:` and specify `Disabled` state. Let me know if it works.

**Comment by DavydLiu** [comment]
Resolving this issue now, please feel free to re-open it if still have problem.
