### ISSUE TITLE
Deselectable radios

### ISSUE THREAD

**Issue by alper** [DavydLiu/DLRadioButton#72]
I like this library but I really need it to be deselectable, so I'm going to see whether I can quickly make that.

**Comment by DavydLiu** [comment]
You mean toggle it? Try set `multipleSelectionEnabled` to `YES`.

**Comment by alper** [comment]
I want to toggle it indeed _but_ I don't want it to be multi-selectable.

**Comment by DavydLiu** [comment]
@alper Sorry, radio buttons are not designed to be able to toggle. You can try to add additional logic to deselect others.

**Comment by alper** [comment]
That's what I did here. It's just the state where they are in at the beginning as well. If I have two of them then at the beginning none of them are in fact selected.

Sometimes people may want to get back to that state.
