### ISSUE TITLE
.selected() or .isSelected ?

### ISSUE THREAD

**Issue by giulioportioli** [DavydLiu/DLRadioButton#74]
With Swift 3.0, I've tried to set a button as selected programmatically thus `myButton.selected()` but the instruction seemed to have no effect.
The only way I managed to get it to work was with `myButton.isSelected = true`. Is this expected, or a bug, or else?
Nice little library anyway. Thank you.

**Comment by DavydLiu** [comment]
`selected` is a property of `UIControl`. `isSelected` is the getter of this property. The idea way of setting it should be `myButton.selected = true`.

**Comment by giulioportioli** [comment]
If I put `myButton.selected = true`, Xcode protests that "selected has been renamed to isSelected". I guess it's a 3.0 thing. I've only known Swift in its last version, so you might be referring to previous versions, I guess.

**Comment by DavydLiu** [comment]
@gbradley Try `button.selected = false`?

**Comment by gbradley** [comment]
That results in the same issue described above, XCode reporting that `selected` has been replaced by `isSelected`.
