### ISSUE TITLE
Missing initial margin for icon on right

### ISSUE THREAD

**Issue by emarwil** [DavydLiu/DLRadioButton#75]
I'm just getting started with DLRadioButton 1.4.9.  When creating a either round or square radio buttons with "Icon on Right", the initial margin seems to be on the right of the button rather than the left.  Once I toggle the button, it realigns properly with a margin between the text and the button.  I'm using the default margin and I have multiple selection enabled.

Also I don't see the button displayed in interface builder (Xcode 8.1) - it shows only the text element of the button.  When displayed a device, the button and text are displayed.

**Comment by DavydLiu** [comment]
Hi, @emarwil could you provide a code smaple for me to take a look at it?

For, interface buidler, I have the same issue. It's probably a Xcode bug.
