### ISSUE TITLE
Using on reusable tableviewcells problem

### ISSUE THREAD

**Issue by rafaellage** [DavydLiu/DLRadioButton#76]
So, i'm using you button as a checkbox on a tableviewcell, the problem is that even using models when the cell is drawn again it dont persists the state. When i start to roll the table it keeps changing. After some digging i've found a solution but i need some explaining to know the reason this is happening.

The problem was here:

`- (void)setSelected:(BOOL)selected {
    if ((self.isMultipleSelectionEnabled ||
        (...)
    }
    
    if (self.isMultipleSelectionEnabled) {
        [super setSelected:!self.isSelected];
    } else {
        [super setSelected:selected];
        if (selected) {
            [self deselectOtherButtons];
        }
    }
}`

The solution i've found was to change to this: 

`- (void)setSelected:(BOOL)selected {
    if ((self.isMultipleSelectionEnabled ||
        (...)
    }
    
    if (self.isMultipleSelectionEnabled) {
        [super setSelected: selected];
    } else {
        [super setSelected:selected];
        if (selected) {
            [self deselectOtherButtons];
        }
    }
}`

Can you explain me why are you using  "[super setSelected:!self.isSelected];"?

EDIT:

Ok, i get it, this way we always get true on setSelected, but i still could not find a solution to work this out. Any help would be appreciated =)

**Comment by DavydLiu** [comment]
So, the reason for using `[super setSelected:!self.isSelected];` is because we want to toggle the radio button if multiple selection is not enabled.
