### ISSUE TITLE
Cannot set the checkbox button programmatically in swift 2

### ISSUE THREAD

**Issue by iasonasiasonos** [DavydLiu/DLRadioButton#77]
I am using swift 2.1 and i cannot set the selected property to true and enable the checkbox button.
I have the .multipleSelectionEnabled = true and i do the following:
myradiobutton.selected = true and it is not working.

**Comment by DavydLiu** [comment]
Looks like for `Swift` is actually `isSelected`. BTW, this property comes from `UIControl`, `DLRadioButton` didn't define it.
