### ISSUE TITLE
VM: DLRadioButton (CALayer)

### ISSUE THREAD

**Issue by eraysezginer** [DavydLiu/DLRadioButton#79]
I'm using DLRadioButton for my local survey application. But I have a problem about memory allocation;

I have sample survey with 50 questions and about 1200 answers (nearly all use DLRadioButton). I use UIScrollView to show question and ViewDidLoad method I create this scroll view. 

Problem is when I allocate buttons it allocates about 1 MB of size for DLRadiButton class. But for VM:DLRadioButton (CALayer) is takes about 100 MB (Checked on Xcode Instruments tool). But main problem is when I quit survey page it doesnt deallocate this CALayers and after 3 times try to open survey app crashes because of memory problem.

I use this method for every answers in for loop ;

 DLRadioButton *firstRadioButton = [[DLRadioButton alloc] initWithFrame:CGRectMake(0, 0, 40, 40)];

What do you suggest me to fix this issue?

Thank you

![ekran resmi 2017-03-29 10 59 00](https://cloud.githubusercontent.com/assets/7392556/24444589/8ff4b6da-146f-11e7-869f-828cb856d9bd.png)

**Comment by DavydLiu** [comment]
I think the answer is quite straight-forward. You should make the survey view (contains `DLRadioButton`) a reusable view.
