### ISSUE TITLE
drawing issue

### ISSUE THREAD

**Issue by bhartsb** [DavydLiu/DLRadioButton#8]
I'm creating the buttons programmatically and adding them to the cell of a tableview.  They are not drawing.

**Comment by DavydLiu** [comment]
Can you post the code for adding buttons programmatically?

**Comment by bhartsb** [comment]
I used the code from your example project.   Might I request that you create an example showing how to put the radio buttons in a table view cell's image view?   Also, I tried to contact you but the link goes to your twitter account.

**Comment by DavydLiu** [comment]
Without any context, it's hard for me tell what exactly going on. Even I made an example with Radio Button in a table view. However, I'm pretty sure that you can't put radio buttons in an image view.

Can you excerpt that part of the code, so I can tell where exactly it went wrong.

**Comment by bhartsb** [comment]
I'm at work presently, but I will try to later tonight.

Thanks.

Brian

**Comment by DavydLiu** [comment]
Closing the issue right now, please feel free to reopen it if you have further questions.
