### ISSUE TITLE
Select some checkbox initially

### ISSUE THREAD

**Issue by AbrahamEP** [DavydLiu/DLRadioButton#83]
How can I select some of my buttons with code? I have a DB and save the info that the user selects, then when the user use the same view it must display the previous selection

**Comment by DavydLiu** [comment]
Yes, you can by using `[yourRadioButton setSelected:YES];`.

**Comment by Gazzini** [comment]
In Swift 3, `firstRadioButton.isSelected = true` does the trick.

**Comment by DavydLiu** [comment]
@AbrahamEP please refer to @Gazzini 's comment.
