### ISSUE TITLE
Initial selection checkbox when page open

### ISSUE THREAD

**Issue by Vibinreji** [DavydLiu/DLRadioButton#85]
I need to set some checkbox selected initially when page open. I tried mycheckbox.isSelected=true
But its not working.

**Comment by saad-ansari** [comment]
yes same issue .... radioButton.selected = true; and [radioButton setSelected:YES]; both is not working.

**Comment by DavydLiu** [comment]
Hey guys, I just tried this in the example app by calling `[firstRadioButton setSelected:YES]` after`firstRadioButton` was created. It worked perfectly. Can you give it a try?

**Comment by Gazzini** [comment]
In Swift 3, `firstRadioButton.isSelected = true` does the trick.

**Comment by DavydLiu** [comment]
@Vibinreji @saad-ansari Please refer to @Gazzini's comment, thanks!
