### ISSUE TITLE
this class is not key value coding-compliant for the key otherButtons

### ISSUE THREAD

**Issue by Binojvj** [DavydLiu/DLRadioButton#86]
I've a UIView in an Xib file with 2 DLRadioButtons connected to each other as otherButtons and working fine.

I'm trying to do the same on another viewController but when I'm connecting them together using otherButtons option, it's simply crashing. Without the connection app is working fine.
There are total 7 DLRadioButtons in this view controller and I've only tried connecting two of them.

Using Xcode 8.2.1 and Swift 3.

**Comment by DavydLiu** [comment]
So, you were trying to connect buttons in operate `ViewController`s? Not sure how this is related to KVC, could you provide an example?
