### ISSUE TITLE
Issue with action inside createRadioButton (in the example project)

### ISSUE THREAD

**Issue by abinodh** [DavydLiu/DLRadioButton#87]
Hi David,

I am getting a few errors when I try to run your example project they are

**1.** "/Users/admin/Downloads/DLRadioButton-master/Example/DLRadioButtonExample/DemoViewController.swift:51:30: Missing argument for parameter 'action' in call" 

**2.** /Users/admin/Downloads/DLRadioButton-master/Example/DLRadioButtonExample/DemoViewController.swift:51:45: Expected expression in list of expressions

**3.** /Users/admin/Downloads/DLRadioButton-master/Example/DLRadioButtonExample/DemoViewController.swift:51:45: Expected ',' separator

All of these errors around this code:
`radioButton.addTarget(self, action: #selector(DemoViewController.logSelectedButton), forControlEvents: UIControlEvents.TouchUpInside);`

inside the function createRadioButton

**Comment by DavydLiu** [comment]
Have your tried to clean and rebuild? Sorry for the late response.
