### ISSUE TITLE
使用storyboard出现的问题

### ISSUE THREAD

**Issue by money150604** [DavydLiu/DLRadioButton#9]
IB Designables
Failed to render instance of DLRadioButton:
Failed to load designables form path (null)

**Comment by DavydLiu** [comment]
Please follow these steps to try to resolve it

1. Clear Xcode derived data for the project. 
2. Do clean/build 
3. in storyboard go to edit and do "update all views" wait for build to be completed and errors should be gone

**Comment by DavydLiu** [comment]
Closing this issue right now, please feel free to reopen it if you have further questions.
