### ISSUE TITLE
Radio icon disappearing

### ISSUE THREAD

**Issue by ptrocki** [DavydLiu/DLRadioButton#94]
Swift 3
version 1.4.9

When I select and then deselect button, radio icon is white. On white background it looks like this disappeared.

**Comment by DavydLiu** [comment]
Could you provide a screenshot? Thanks!

**Comment by ptrocki** [comment]
Sorry for big delay, I am back. 
![simulator screen shot 14 jun 2017 07 27 16](https://user-images.githubusercontent.com/12766071/27116795-7c57d530-50d3-11e7-8b84-a50836abd8bf.png)
![simulator screen shot 14 jun 2017 07 27 23](https://user-images.githubusercontent.com/12766071/27116796-7c5a97e8-50d3-11e7-8e18-6cf2575002e6.png)
![simulator screen shot 14 jun 2017 07 27 26](https://user-images.githubusercontent.com/12766071/27116794-7c577e78-50d3-11e7-8b2b-c1f9a33a13b3.png)

This is a code 
```
  fileprivate func setupRadioButtons() {
    payForEveryoneRadioButton.otherButtons = [payForYourselfRadioButton]
    payForEveryoneRadioButton.iconColor = ColorTheme.appTheme.linkFont
    payForEveryoneRadioButton.indicatorColor = ColorTheme.appTheme.linkFont
    payForEveryoneRadioButton.tintColor = ColorTheme.appTheme.linkFont
    payForEveryoneRadioButton.setTitleColor(UIColor.black, for: UIControlState())
    payForYourselfRadioButton.iconColor = ColorTheme.appTheme.linkFont
    payForYourselfRadioButton.indicatorColor = ColorTheme.appTheme.linkFont
    payForYourselfRadioButton.tintColor = ColorTheme.appTheme.linkFont
    payForYourselfRadioButton.setTitleColor(UIColor.black, for: UIControlState())
  }
```
I also tried code from you example and also does not work. This buttons are in stackview.

**Comment by DavydLiu** [comment]
Looks like to me something went wrong around radio button's selected state. Have you tried not setting the tint color? e.g. just plain old default radio button.

**Comment by Sk8er22** [comment]
https://github.com/DavydLiu/DLRadioButton/raw/master/Images/change_UIButton_type.png

Be sure than you set custom on type button!

**Comment by DavydLiu** [comment]
@ptrocki, did set button type to custom fix the issue?

**Comment by ptrocki** [comment]
Yes, TY. You can close this :)
