### ISSUE TITLE
RadioButton Icons not appearing in xcode 8.3

### ISSUE THREAD

**Issue by Prabu-raj** [DavydLiu/DLRadioButton#97]
I am unable to see any of the icons for the radio buttons in icons dropdown except my own set of icons.

**Comment by DavydLiu** [comment]
Can you be more specific about the "icons dropdown"? Not sure what does that mean.

**Comment by Prabu-raj** [comment]
Icons such as circle, handshake are displayed in the dropdown list and they are also not visible in the uiview in the interface builder. Default circle icon is displayed only on running the app.

**Comment by DavydLiu** [comment]
Did you change the UIButton type to `custom`

![Set DLRadioButton to custom](https://github.com/DavydLiu/DLRadioButton/raw/master/Images/change_UIButton_type.png)

**Comment by DavydLiu** [comment]
Closing the issue for now.
