### ISSUE TITLE
Title and image inset not working

### ISSUE THREAD

**Issue by vbicer** [DavydLiu/DLRadioButton#98]
I want to give inset to title from left and to image from from right. But I am not able to do that.

![image](https://user-images.githubusercontent.com/6940882/28877157-26cd14de-77a4-11e7-9320-1983c573888d.png)

Below code won't work. How can I accomplish that?

                    let button = createCheckBoxButton(item, with: buttonFrame)
                    button.titleEdgeInsets = UIEdgeInsetsMake(0, 10, 0, 0)
                    button.imageEdgeInsets = UIEdgeInsetsMake(0, 0, 0, 10)

**Comment by DavydLiu** [comment]
Sorry for the late reply, have been super busy for the past couple of months. Were you able to figure it out?

**Comment by vbicer** [comment]
Ahh, hello again. Actually I couldn't fix the issue. So decided to created custom component.
